services:
  postgres:
    container_name: 'todolist-database'
    image: 'postgres:latest'
    environment:
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_USER=${POSTGRES_USER}"
    ports:
      - 5432:5432
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./postgres/scripts
        target: /docker-entrypoint-initdb.d

volumes:
  postgres-data:
    name: todolist-postgres-data
